# Configuration file for packaging

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "osl-foundation"
version = "0.0.1"
description = "OHBA Software Libary: Foundation Models"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Linux",
]

[project.urls]
Homepage = "https://github.com/OHBA-analysis/osl-foundation"
Issues = "https://github.com/OHBA-analysis/osl-foundation/issues"

[tool.setuptools.packages.find]
include = ["osl_foundation"]
