model_config:
  pretrained_model:
    model_path: ../../models/meg-gpt
    checkpoint: latest
    pretrained_layers:
      - input_embedding
      - decoder
      - prediction_head
  decoder_parameters:
    channel_attention_dropout: 1.0
    dropout: 0.2
    feed_forward_activation: leaky_relu
    feed_forward_dim: 400
    latent_sequence_length: 40
    model_dim: 400
    n_heads: 4
    n_layers: 4
    n_patches: 20
    patch_length: 4
    unpatched_length: 16
    within_channel_attention_dropout: 0.0
  input_parameters:
    channel_embedding_dim: 400
    embedding_dim: 400
    pos_embedding_dim: 400
    token_embedding_dim: 400
  loss_parameters:
    loss_sequence_length: 8
  n_channels: 52
  name: meg_gpt
  sequence_length: 80
training_config:
  batch_size: 16
  n_epochs: 10
  optimizer:
    learning_rate: 5.0e-07
  checkpoint:
    save_dir: ../../models/decoding_model