model_config:
  decoder_parameters:
    channel_attention_dropout: 0.0
    dropout: 0.2
    feed_forward_dim: 400
    latent_sequence_length: 40
    model_dim: 400
    n_heads: 4
    n_layers: 4
    n_patches: 20
    patch_length: 4
    unpatched_length: 16
    within_channel_attention_dropout: 0.0
  input_parameters:
    channel_embedding_dim: 400
    embedding_dim: 400
    extra_labels:
    - label_dim: 400
      n_classes: 612
      name: session_id
    pos_embedding_dim: 400
    token_embedding_dim: 400
  loss_parameters:
    loss_sequence_length: 8
  n_channels: 52
  name: ephys_gpt
  sequence_length: 80
  tokenizer_path: ../models/tokenizer
training_config:
  batch_size: 8
  n_epochs: 1
  optimizer:
    learning_rate: 1.0e-05
  multi_gpu: True
  checkpoint:
    save_dir: models/generator